### ISSUE TITLE
Reobfuscation doesn’t work

### ISSUE THREAD

**Issue by mineLdiver** [ModificationStation/1.7.3-LTS#15]
I made a small addition into net.minecraft.client.Minecraft (added a line in the “main” method), recompiled, reobfuscated, tried running it in MultiMC, but it failed. Then, I decompiled the reobfuscated code with Luyten and it wasn’t obfuscated at all.

**Comment by Dereku** [comment]
Can you attach your patch of ``Minecraft.java``?

**Comment by mineLdiver** [comment]
Can’t atm, but I just added “ClassLoadingManager.INSTANCE.init(args, Side.CLIENT);” line as the first line in “main” that initializes StationLoader

**Comment by Johnanater** [comment]
Should be fixed as of #17 .

Will reopen if there's any more issues.
