### ISSUE TITLE
TileEntities are broken

### ISSUE THREAD

**Issue by mineLdiver** [ModificationStation/1.7.3-LTS#22]
TileEntities shouldn't override "onInventoryChanged". Super class's TileEntity method y_ must have a "onInventoryChanged" mapping and everything will be fixed without overriding "onInventoryChanged" with an empty method. Right now TileEntities will just behave very broken.

**Comment by calmilamsy** [comment]
Still an issue in lts:python3.

**Comment by Dereku** [comment]
I remember exactly what I added this method in the patches. 
Ok, it's time to restore my workspace :^)

**Comment by calmilamsy** [comment]
@Dereku awesome. Will work on fixes for the other versions in lts:python3 once you add your patch.

**Comment by Dereku** [comment]
@calmilamsy , check it out.

**Comment by mineLdiver** [comment]
Should be fixed in #23 pull. Will be opened if still presents
