### ISSUE TITLE
Minecraft Server b1.9-pre5 link has wrong binary file.

### ISSUE THREAD

**Issue by Dereku** [ModificationStation/1.7.3-LTS#28]
Download link https://github.com/ModificationStation/1.7.3-LTS/blob/master/runtime/minecraftversions.py#L288 provides Minecraft Server b1.9-pre4 instead of pre5.

Change it to http://assets.minecraft.net/1_9-pre5/minecraft_server.jar or someone will update the binary on a files.pymcl.net?

@calmilamsy, hello.

**Comment by calmilamsy** [comment]
Will fix on files.pymcl.net as well as change the link in the list.

Thanks for pointing that out!
