### ISSUE TITLE
Errors while running setup.bat

### ISSUE THREAD

**Issue by iBars** [ModificationStation/1.7.3-LTS#30]
https://pastebin.com/raw/PFGkLZez

**Comment by calmilamsy** [comment]
Fixed in 4fa4c07.
Reopen if issue persists.

**Comment by iBars** [comment]
New URLs are also wrong. Use `https://repo1.maven.org` instead of `https://central.maven.org`

**Comment by Johnanater** [comment]
Fixed :)
