### ISSUE TITLE
Problems with recompiling/reobfuscation

### ISSUE THREAD

**Issue by CodeBasePW** [ModificationStation/1.7.3-LTS#7]
So I've been working on a mod, and it won't reobfuscate for whatever reason. I used to use the actual mcp43 to do all my modding, but someone recommended I try this because it's less buggy. However, I'm still having the same problem as before. Of course I've been trying for days to figure this out on my own, but it seems no matter what I do the problem persists.

Note: This appears to only happen specifically with the code I wrote for this mod and I'm not sure why. (There are no compiler errors in eclipse and I can run the game from eclipse just fine.)

[Here's a screenshot of the entire output.](https://i.imgur.com/FmxRffp.png)

I'm also aware that it clearly says temp/client_reobf.jar is missing, but I have no idea why that's happening. Another thing I should mention is that the script would previously give me output about files being obfuscated before giving this error, but now I don't even get that. It stopped after I ran the updatemd5 script.

**Comment by Johnanater** [comment]
Could you upload logs\mcp.log?

**Comment by CodeBasePW** [comment]
Yeah sorry, I left it out because it doesn't look like there's any useful information in it. https://pastebin.com/w7ywZMe0

**Comment by Johnanater** [comment]
Weird, what are you trying to do?

**Comment by CodeBasePW** [comment]
Well I'm doing a variety of things. I've written a basic sort of framework with an event system and such and I've just added hooks everywhere in the Minecraft code. The majority of the code isn't in any of the Minecraft classes. I thought that maybe it has something to do with me removing the resource filters that are added to the eclipse workspace by default, but I can't imagine that would break reobfuscation. I don't have too many details to give you since I'm doing a fairly straightforward client to replace a donator mod for a server I play on. I haven't done anything out of the ordinary development-wise.

**Comment by mineLdiver** [comment]
Can you please send RetroGuard's log instead of mcp.log? It seems to be more useful, according to the log you sent.

**Comment by CodeBasePW** [comment]
Well I didn't even know there was a RetroGuard log, and I feel incredibly stupid but apparently one of my classes is corrupt. I'm literally looking at the code for it in eclipse right now so I'm not sure how it's corrupt or how I'm supposed to fix it. Here's the log: https://pastebin.com/an8Quejr

**Comment by CodeBasePW** [comment]
Here's the code of the class in question if that helps. https://pastebin.com/EAfyeZuy

**Comment by mineLdiver** [comment]
I’m absolutely not sure if it helps, but try to put “Type” enum before Event’s constructor. This might be the problem.

**Comment by CodeBasePW** [comment]
Tried that, and the RetroGuard log didn't change at all (except for the timestamps) and the script output did give me something new about finding the modified Event class, but it ended right after that with the same error as before.

**Comment by CodeBasePW** [comment]
I renamed the Event class to something else and the error changed to a different class, however after changing the names of several classes, the error returned to the Event class for whatever reason.

**Comment by edwan192** [comment]
According to [retroguard's src](https://github.com/agaricusb/retroguard-gpl/blob/c7e28cd2aa7303bb8ff53947fc8874d7bfb1eef8/src/main/java/COM/rl/obf/classfile/CpInfo.java#L68) it has to do with something in byte code not being recognized, which triggers [An error](https://github.com/agaricusb/retroguard-gpl/blob/c7e28cd2aa7303bb8ff53947fc8874d7bfb1eef8/src/main/java/COM/rl/obf/GuardDB.java#L113). Maybe the lambda is causing it?

**Comment by CodeBasePW** [comment]
I was afraid that was it. I'll remove the lambda and see if it starts playing nice.

**Comment by CodeBasePW** [comment]
Well now it's bothering me about the EventManager class which I didn't write in the first place, and it uses a LOT of lambdas. I think you found the problem.

**Comment by edwan192** [comment]
You're welcome. @Johnanater maybe you can close the issue now?

**Comment by Johnanater** [comment]
@CodeBasePW Maybe now that SpecialSource has been merged this will work?

**Comment by CodeBasePW** [comment]
@Johnanater I should've clarified before for others that the problem was actually the lambdas. I haven't had any problems outside of this issue.
